version: '3'

services:

  db:
    image: "mysql"
    restart: always
    environment:
      MYSQL_DATABASE: biblia_db
      MYSQL_ROOT_PASSWORD: znoksy139
    ports:
      - '3060:3306'
    expose:
      - '3060'
    volumes:
    - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pznoksy139"]
      interval: 5s
      timeout: 20s
      retries: 10


  app:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - ./backend/.env.dev

volumes:
  db:

      